services:
  app:
    build: .
  db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: mypassword

secrets:
  db_url:
    environment: DATABASE_URL
  db_username:
    environment: DATABASE_USERNAME
  db_password:
    environment: DATABASE_PASSWORD